version: 2.1
  jobs:
    build:
      docker:
          - image: circleci/node:12.16
            steps:
              - checkout
              - run: echo "build project"

orbs:
  node: circleci/node@4.7

workflows:
  testing:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: yarn       
      - build