version: 2.1

orbs:
  node: circleci/node@4.7
  
jobs:
  build:
    steps:
      - run: echo "build project"

workflows:
  testing:
    jobs: 
      - node/test:
          requires:
            - build
          version: '16.10'
          pkg-manager: yarn
       