version: 2.1

orbs:
  node: circleci/node@4.7
  
jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: build
      - run:
          command: ls
          name: ls    
      - persist_to_workspace:
          root: ~/build
          paths:
            - ./build
  deploy:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - attach_workspace:
          at: ~/project 

workflows:
  testing:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: yarn
      - build