version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  testing:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: yarn       
      - node/build:
          version: '16.10'
          pkg-manager: yarn  