version: 2.1

orbs:
  node: circleci/node@4.7
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.2.1

jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: build
      - run:
          command: ls
          name: ls
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./build
  deploy:
    docker:
      - image: cimg/node:14.0.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: ~/project
      - run:
          command: ls
          name: ls
#      - run: 
#          name: docker_build
#          command: docker build -t company/app:$CIRCLE_SHA1 .

workflows:
  testing:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: yarn     
  deploy:
    jobs:
      - build: 
        filters:
          branches:
            only:
              - main
#      - deploy:
#          requires:
#            - build
#          filters:
#            branches:
#              only:
#                - main
      - aws-ecr/build-and-push-image:
          requires:
            - build
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          attach-workspace: true