version: 2.1

orbs:
  node: circleci/node@4.7
  
workflows:
  version: 2
  build:
    jobs: 
      - build

jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: echo "build project"        