version: 2.1

orbs:
  node: circleci/node@4.7
  
jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run:
          command: yarn build
          name: build

workflows:
  testing:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: yarn
      - build